


---
- name: Installing apache2
  hosts: 192.168.60.23
  vars:
   a: apache2
   b: present
   c: no
  tasks:
   - name: Installing apache2
     apt:
      name: "{{a}}"
      state: "{{b}}"
      update_cache: "{{c}}"



...
